### ISSUE TITLE
[DSC] InvalidOperation: PowerShell DSC resource MSFT_PackageManagement  failed to execute Set-TargetResource functionality with error message

### ISSUE THREAD

**Issue by DSpirit** [ethanbergstrom/winget#13]
## Setup
When using your example DSC gist on an Azure Windows 11 VM (it also happened on a Windows 10 VM), the WinGet provider gets installed but the packages couldn't be found.
WinGet CLI is installed properly with `v1.3.269`

OS Info:
```
Name                           Value
----                           -----
PSVersion                      7.2.8
PSEdition                      Core
GitCommitId                    7.2.8
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Error Message
```
InvalidOperation: PowerShell DSC resource MSFT_PackageManagement  failed to execute Set-TargetResource functionality with error message: No match was found for the specified search criteria and package name '7zip.7zip'. Try Get-PackageSource to see all available registered package sources. 
InvalidOperation: PowerShell DSC resource MSFT_PackageManagement  failed to execute Set-TargetResource functionality with error message: No match was found for the specified search criteria and package name 'Balena.Etcher'. Try Get-PackageSource to see all available registered package sources. 
....
```
The only thing that helps, is running the 
`Find-Package -Name 7zip.7zip -ProviderName "winget"` 
manually, then it seems to register something and the DSC runs just fine.

## Steps to reproduce
1. Create a .ps1 file with your gist
2. Run the gist as a local administrator

## What I've tried so far
I've tried running the `Find-Package` also in DSC, but even after running `Get-PackageProvider WinGet` and `Get-PackageSource -ProviderName "WinGet"` (which are returning the perfectly fine installed sources), I just seems to *demand* a manual intervention as errors occur like stated above.

Any help would be highly appreciated!

**Comment by ethanbergstrom** [comment]
Hm..offhand, I don't know what would cause that. 

WinGet does require a couple initialization steps (creating the execution alias, caching package information) so I wonder if one of those things gets triggered when running a command interactively that isn't able to take place when invoked by DSC. We're invoking WinGet via command line, and it is kind of wonky until an official, stable PowerShell module is available.

You might also look at the WinGet logs (C:\Users\<username>\AppData\Local\Packages\Microsoft.DesktopAppInstaller\LocalState\DiagOutputDir\ or something like that) to get a sense of whether WinGet is getting invoked at all, and if it is, whether it's throwing any errors.

**Comment by DSpirit** [comment]
Many thanks for the quick answer!
Maybe I'll just wait til then, for now I'm good with choco as well :)
As I love the idea of auto-updating the packages, I hope to come back here when we have a stable version. Keep it up!
