### ISSUE TITLE
Broken release notes link on Powershell Gallery

### ISSUE THREAD

**Issue by andresharpe** [ethanbergstrom/winget#3]
https://github.com/ethanbergstrom/WinGet/blob/current/CHANGELOG.md responds with 404

Linked from: https://www.powershellgallery.com/packages/WinGet/0.0.1

**Comment by ethanbergstrom** [comment]
Thanks for the contribution!

Fixed in [this commit](https://github.com/ethanbergstrom/winget/commit/9bc7c808c2e8b6415038a1bb7f27be16c0156442) and will take effect on PSGallery with the next release of the module.
