### ISSUE TITLE
Get-InstalledPackage Errors

### ISSUE THREAD

**Issue by Kizan** [ethanbergstrom/winget#5]
With WinGet installed on the system (tested).

Import-Module Cobalt
Import-Module WinGet

Get-InstalledPackage

Generates the following error:
```
New-SoftwareIdentity : The term 'New-SoftwareIdentity' is not recognized as the name of a cmdlet, function, script file, 
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try    
again.
At C:\Users\blah\Documents\WindowsPowerShell\Modules\WinGet\0.0.4\private\ConvertTo-SoftwareIdentity.ps1:35 char:5        
+                 New-SoftwareIdentity @swid
+                 ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-SoftwareIdentity:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
    
  I'm sure I screwed up. What did I screw up?

Thanks,

Kizan

**Comment by ethanbergstrom** [comment]
Hey @Kizan 

With PackageManagement providers like this module, you shouldn't run `Import-Module` on either the main module or its dependencies (which will pull in automatically).

Check out [the readme](https://github.com/ethanbergstrom/winget#install-winget) for more information on proper usage.
