### ISSUE TITLE
Find-Package does only exact searchs

### ISSUE THREAD

**Issue by Lockszmith-GH** [ethanbergstrom/winget#7]
```ps1
cobalt\Find-WinGetPackage 'vlc'
```
returns the package `VideoLAN.VLC`

while
```ps1
Find-Package -ProviderName WinGet -Name 'vlc'
```
returns an error.

It seems that [~3 months ago](https://github.com/ethanbergstrom/winget/commit/7bb41f0ebee89f1b5f574dda7d3d0c83b7a44042?diff=split#diff-ebe3925e29c25d620684b55444abbac417cd3554e2f2d4b5dac8f050d95e1981R60)  it was setup with the `-Exact` switch.

Any particular reason for that?
Can this be removed, or at least provided as a choice?

**Comment by ethanbergstrom** [comment]
Hey @Lockszmith-GH 

The 'exact' behavior on by default dramatically simplifies WinGet's complicated and ambiguous results that come from the multitude of ways it searches for a package, which makes it more conducive to automation (the `Install-Package` cmdlet actually calls `Find-Package` cmdlet behind the scenes to return a fast package reference string).

If you're looking for something that most closely reflects the behavior of winget CLI, I would recommend using Cobalt, whereas the WinGet package provider is very opinionated.

**Comment by Lockszmith-GH** [comment]
Thank you for the quick response.

Since Cobalt is so tightly bound, I see your point.

It would make it easier to find the information if Cobalt would be linked in the README.md (it's not mentioned at all)

In anyway, thanks for explaining.
